<?php

namespace Database\Seeders;

use App\Models\ShopItem;
use Illuminate\Database\Seeder;

class ShopItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ════════════════════════════════════════════════════════════════
            // ── BORDERS (50) ─────────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════

            // Common (15)
            ['slug' => 'border-gold-ring',       'name' => 'Gouden Ring',         'description' => 'Een glanzende gouden rand om je avatar.',                    'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-yellow-400',                                        'level_required' => 0],
            ['slug' => 'border-ocean-blue',      'name' => 'Oceaan Blauw',        'description' => 'Een koele blauwe gloed rond je avatar.',                      'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-blue-400',                                          'level_required' => 0],
            ['slug' => 'border-rose',            'name' => 'Roze Droom',          'description' => 'Een zachte roze rand voor de romantics.',                     'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-pink-400',                                          'level_required' => 0],
            ['slug' => 'border-slate',           'name' => 'Stalen Grijs',        'description' => 'Minimalistisch en strak.',                                    'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-slate-400',                                         'level_required' => 0],
            ['slug' => 'border-white',           'name' => 'Sneeuwwit',           'description' => 'Puur en schoon als verse sneeuw.',                            'type' => 'border', 'rarity' => 'common',    'price' => 40,   'css_class' => 'ring-4 ring-white',                                             'level_required' => 0],
            ['slug' => 'border-stone',           'name' => 'Steen',               'description' => 'Solide als een rots.',                                        'type' => 'border', 'rarity' => 'common',    'price' => 40,   'css_class' => 'ring-4 ring-stone-400',                                         'level_required' => 0],
            ['slug' => 'border-red',             'name' => 'Vuurrood',            'description' => 'Fel rood als een brandweerwagen.',                            'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-red-400',                                           'level_required' => 0],
            ['slug' => 'border-lime',            'name' => 'Limoen',              'description' => 'Fris en zuur als een limoen.',                                'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-lime-400',                                          'level_required' => 0],
            ['slug' => 'border-violet',          'name' => 'Violet',              'description' => 'Koninklijk violet voor een elegante look.',                   'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-violet-400',                                        'level_required' => 0],
            ['slug' => 'border-sky',             'name' => 'Hemelsblauw',         'description' => 'Licht als de lucht op een zomerdag.',                         'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-sky-400',                                           'level_required' => 0],
            ['slug' => 'border-indigo',          'name' => 'Indigo',              'description' => 'Diep en mysterieus als de nachtlucht.',                       'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-indigo-400',                                        'level_required' => 0],
            ['slug' => 'border-teal',            'name' => 'Turquoise',           'description' => 'De kleur van tropische zeeën.',                               'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-teal-400',                                          'level_required' => 0],
            ['slug' => 'border-fuchsia',         'name' => 'Fuchsia',             'description' => 'Opvallend en onvergetelijk.',                                 'type' => 'border', 'rarity' => 'common',    'price' => 50,   'css_class' => 'ring-4 ring-fuchsia-400',                                       'level_required' => 0],
            ['slug' => 'border-zinc',            'name' => 'Zink',                'description' => 'Industrieel en stoer.',                                       'type' => 'border', 'rarity' => 'common',    'price' => 40,   'css_class' => 'ring-4 ring-zinc-400',                                          'level_required' => 0],
            ['slug' => 'border-thin-gold',       'name' => 'Dun Goud',            'description' => 'Subtiel goud, minder is meer.',                              'type' => 'border', 'rarity' => 'common',    'price' => 40,   'css_class' => 'ring-2 ring-yellow-400',                                        'level_required' => 0],

            // Rare (15)
            ['slug' => 'border-emerald',         'name' => 'Smaragd',             'description' => 'Een frisse groene rand die opvalt.',                          'type' => 'border', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'ring-4 ring-emerald-500',                                       'level_required' => 3],
            ['slug' => 'border-amber',           'name' => 'Amber Gloed',         'description' => 'Warm als een zonsondergang.',                                 'type' => 'border', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'ring-4 ring-amber-500',                                         'level_required' => 3],
            ['slug' => 'border-cyan',            'name' => 'Ijzig Blauw',         'description' => 'Koud als ijs, scherp als een diamant.',                       'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-4 ring-cyan-400',                                          'level_required' => 4],
            ['slug' => 'border-double-gold',     'name' => 'Dubbel Goud',         'description' => 'Twee lagen goud voor extra prestige.',                        'type' => 'border', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'ring-4 ring-yellow-500 ring-offset-2 ring-offset-yellow-200',   'level_required' => 5],
            ['slug' => 'border-double-blue',     'name' => 'Dubbel Blauw',        'description' => 'Twee lagen blauw, dubbel zo cool.',                          'type' => 'border', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'ring-4 ring-blue-500 ring-offset-2 ring-offset-blue-200',       'level_required' => 5],
            ['slug' => 'border-double-rose',     'name' => 'Dubbel Roze',         'description' => 'Twee lagen roze voor extra lief.',                            'type' => 'border', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'ring-4 ring-pink-500 ring-offset-2 ring-offset-pink-200',       'level_required' => 5],
            ['slug' => 'border-thick-emerald',   'name' => 'Dik Smaragd',         'description' => 'Extra dikke smaragd ring. Niet te missen.',                   'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-[6px] ring-emerald-500',                                   'level_required' => 4],
            ['slug' => 'border-thick-purple',    'name' => 'Dik Paars',           'description' => 'Dikke paarse rand voor een krachtige look.',                  'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-[6px] ring-purple-500',                                    'level_required' => 4],
            ['slug' => 'border-coral',           'name' => 'Koraal',              'description' => 'Warm als een tropisch rif.',                                  'type' => 'border', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'ring-4 ring-rose-400',                                          'level_required' => 3],
            ['slug' => 'border-mint',            'name' => 'Mint',                'description' => 'Fris als pepermunt.',                                         'type' => 'border', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'ring-4 ring-green-300',                                         'level_required' => 3],
            ['slug' => 'border-sunset-orange',   'name' => 'Zonsondergang',       'description' => 'Warme oranje tonen als de zon zakt.',                         'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-4 ring-orange-500',                                        'level_required' => 4],
            ['slug' => 'border-lavender',        'name' => 'Lavendel',            'description' => 'Zacht en rustgevend als een lavendelveld.',                   'type' => 'border', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'ring-4 ring-purple-300',                                        'level_required' => 3],
            ['slug' => 'border-double-red',      'name' => 'Dubbel Rood',         'description' => 'Twee lagen rood. Dubbel gevaarlijk.',                         'type' => 'border', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'ring-4 ring-red-500 ring-offset-2 ring-offset-red-200',         'level_required' => 5],
            ['slug' => 'border-champagne',       'name' => 'Champagne',           'description' => 'Bubbels en klasse.',                                         'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-4 ring-amber-300',                                         'level_required' => 4],
            ['slug' => 'border-deep-ocean',      'name' => 'Diepzee',             'description' => 'Donkerblauw als de diepste oceaan.',                          'type' => 'border', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'ring-4 ring-blue-700',                                          'level_required' => 4],

            // Epic (12)
            ['slug' => 'border-neon-pulse',      'name' => 'Neon Pulse',          'description' => 'Een pulserende neon paarse rand.',                            'type' => 'border', 'rarity' => 'epic',      'price' => 200,  'css_class' => 'ring-4 ring-purple-500 shadow-lg shadow-purple-500/30',         'level_required' => 5],
            ['slug' => 'border-electric',        'name' => 'Elektrisch',          'description' => 'Geladen met energie.',                                        'type' => 'border', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'ring-4 ring-sky-400 shadow-lg shadow-sky-400/30',               'level_required' => 7],
            ['slug' => 'border-toxic',           'name' => 'Giftig Groen',        'description' => 'Radioactief groene gloed. Gevaarlijk mooi.',                   'type' => 'border', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'ring-4 ring-lime-400 shadow-lg shadow-lime-400/30',             'level_required' => 8],
            ['slug' => 'border-blood-moon',      'name' => 'Bloedmaan',           'description' => 'Duistere rode gloed als de maan.',                            'type' => 'border', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'ring-4 ring-red-600 shadow-lg shadow-red-600/30',               'level_required' => 10],
            ['slug' => 'border-neon-pink',       'name' => 'Neon Roze',           'description' => 'Felroze neonlicht. Party vibes.',                             'type' => 'border', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'ring-4 ring-pink-500 shadow-lg shadow-pink-500/30',             'level_required' => 7],
            ['slug' => 'border-neon-cyan',       'name' => 'Neon Cyan',           'description' => 'Cyberpunk vibes met neon cyan.',                              'type' => 'border', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'ring-4 ring-cyan-400 shadow-lg shadow-cyan-400/30',             'level_required' => 7],
            ['slug' => 'border-golden-glow',     'name' => 'Gouden Gloed',        'description' => 'Stralend goud met een warme gloed.',                          'type' => 'border', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'ring-4 ring-yellow-400 shadow-lg shadow-yellow-400/30',         'level_required' => 8],
            ['slug' => 'border-emerald-glow',    'name' => 'Smaragd Gloed',       'description' => 'Magisch groene aura rond je avatar.',                         'type' => 'border', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'ring-4 ring-emerald-400 shadow-lg shadow-emerald-400/30',       'level_required' => 8],
            ['slug' => 'border-double-neon',     'name' => 'Dubbel Neon',         'description' => 'Dubbele neon ring. Twee keer zo vet.',                        'type' => 'border', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'ring-4 ring-violet-500 ring-offset-2 ring-offset-violet-300 shadow-lg shadow-violet-500/30', 'level_required' => 9],
            ['slug' => 'border-frost',           'name' => 'Bevroren',            'description' => 'Ijskoud met een bevroren gloed.',                             'type' => 'border', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'ring-4 ring-blue-300 shadow-lg shadow-blue-300/30',             'level_required' => 8],
            ['slug' => 'border-magma',           'name' => 'Magma',               'description' => 'Gloeiend heet als gesmolten lava.',                           'type' => 'border', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'ring-4 ring-orange-600 shadow-lg shadow-orange-600/30',         'level_required' => 9],
            ['slug' => 'border-amethyst',        'name' => 'Amethist',            'description' => 'De kracht van een edelsteen.',                                'type' => 'border', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'ring-4 ring-purple-400 shadow-lg shadow-purple-400/30',         'level_required' => 8],

            // Legendary (8)
            ['slug' => 'border-flame',           'name' => 'Vlammend',            'description' => 'Een vurige rand voor echte kampioenen.',                       'type' => 'border', 'rarity' => 'legendary', 'price' => 400,  'css_class' => 'ring-4 ring-orange-500 shadow-xl shadow-orange-500/40',         'level_required' => 12],
            ['slug' => 'border-diamond',         'name' => 'Diamanten Rand',      'description' => 'Schittert als duizend diamanten.',                            'type' => 'border', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'ring-4 ring-cyan-300 shadow-xl shadow-cyan-300/40',             'level_required' => 15],
            ['slug' => 'border-void',            'name' => 'Void Portal',         'description' => 'Een mysterieuze donkere rand uit het niets.',                  'type' => 'border', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'ring-4 ring-violet-600 shadow-xl shadow-violet-600/50',         'level_required' => 20],
            ['slug' => 'border-solar-flare',     'name' => 'Zonnevlam',           'description' => 'De kracht van de zon rond je avatar.',                         'type' => 'border', 'rarity' => 'legendary', 'price' => 450,  'css_class' => 'ring-[6px] ring-amber-400 shadow-xl shadow-amber-400/40',       'level_required' => 14],
            ['slug' => 'border-plasma',          'name' => 'Plasma Ring',         'description' => 'Puur energie in ringvorm.',                                   'type' => 'border', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'ring-[6px] ring-sky-400 shadow-xl shadow-sky-400/50',           'level_required' => 16],
            ['slug' => 'border-obsidian',        'name' => 'Obsidiaan',           'description' => 'Donker als de nacht, hard als steen.',                         'type' => 'border', 'rarity' => 'legendary', 'price' => 450,  'css_class' => 'ring-[6px] ring-gray-900 shadow-xl shadow-gray-900/50',         'level_required' => 13],
            ['slug' => 'border-supernova',       'name' => 'Supernova',           'description' => 'Een explosie van licht en kleur.',                             'type' => 'border', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'ring-[6px] ring-rose-500 shadow-xl shadow-rose-500/50',         'level_required' => 18],
            ['slug' => 'border-mythic-gold',     'name' => 'Mythisch Goud',       'description' => 'De ultieme gouden rand. Alleen voor legendes.',               'type' => 'border', 'rarity' => 'legendary', 'price' => 650,  'css_class' => 'ring-[6px] ring-yellow-300 shadow-xl shadow-yellow-300/50',     'level_required' => 20],

            // ════════════════════════════════════════════════════════════════
            // ── HATS (50) ────────────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════

            // Common (15)
            ['slug' => 'hat-party',              'name' => 'Feestmuts',            'description' => 'Een kleurrijke feestmuts op je avatar.',                     'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-party',              'level_required' => 0],
            ['slug' => 'hat-cap',                'name' => 'Petje',                'description' => 'Een casual petje. Keep it simple.',                          'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-cap',                'level_required' => 0],
            ['slug' => 'hat-beanie',             'name' => 'Beanie',               'description' => 'Een warme muts voor koude dagen.',                           'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-beanie',             'level_required' => 0],
            ['slug' => 'hat-headband',           'name' => 'Hoofdband',            'description' => 'Sportief en praktisch.',                                     'type' => 'hat', 'rarity' => 'common',    'price' => 60,   'css_class' => 'hat-headband',           'level_required' => 0],
            ['slug' => 'hat-backwards-cap',      'name' => 'Achterstevoren Petje', 'description' => 'Cool kids dragen hun petje achterstevoren.',                'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-backwards-cap',      'level_required' => 0],
            ['slug' => 'hat-bucket',             'name' => 'Bucket Hat',           'description' => 'Relaxed festival vibes.',                                    'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-bucket',             'level_required' => 0],
            ['slug' => 'hat-beret',              'name' => 'Baret',                'description' => 'Très chic! Een kunstzinnige baret.',                         'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-beret',              'level_required' => 0],
            ['slug' => 'hat-flower-crown',       'name' => 'Bloemenkrans',         'description' => 'Een krans van wilde bloemen.',                               'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-flower-crown',       'level_required' => 0],
            ['slug' => 'hat-bandana',            'name' => 'Bandana',              'description' => 'Stoer en rebel.',                                            'type' => 'hat', 'rarity' => 'common',    'price' => 60,   'css_class' => 'hat-bandana',            'level_required' => 0],
            ['slug' => 'hat-straw',              'name' => 'Strohoed',             'description' => 'Perfect voor een zomerse dag.',                              'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-straw',              'level_required' => 0],
            ['slug' => 'hat-propeller',          'name' => 'Propellerpetje',       'description' => 'Wie zegt dat volwassenen geen lol mogen hebben?',            'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-propeller',          'level_required' => 0],
            ['slug' => 'hat-ear-muffs',          'name' => 'Oorwarmers',           'description' => 'Warm en gezellig in de winter.',                             'type' => 'hat', 'rarity' => 'common',    'price' => 60,   'css_class' => 'hat-ear-muffs',          'level_required' => 0],
            ['slug' => 'hat-visor',              'name' => 'Zonneklep',            'description' => 'Bescherming tegen de zon met stijl.',                        'type' => 'hat', 'rarity' => 'common',    'price' => 60,   'css_class' => 'hat-visor',              'level_required' => 0],
            ['slug' => 'hat-newsboy',            'name' => 'Krantenjongen Pet',    'description' => 'Retro vibes uit de jaren 20.',                               'type' => 'hat', 'rarity' => 'common',    'price' => 75,   'css_class' => 'hat-newsboy',            'level_required' => 0],
            ['slug' => 'hat-bow',                'name' => 'Strik',                'description' => 'Een schattige strik op je hoofd.',                           'type' => 'hat', 'rarity' => 'common',    'price' => 60,   'css_class' => 'hat-bow',                'level_required' => 0],

            // Rare (15)
            ['slug' => 'hat-wizard',             'name' => 'Tovenaars Hoed',       'description' => 'Een mystieke hoed voor wijze spelers.',                      'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-wizard',             'level_required' => 3],
            ['slug' => 'hat-santa',              'name' => 'Kerstmuts',            'description' => 'Ho ho ho! Een feestelijke kerstmuts.',                       'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-santa',              'level_required' => 2],
            ['slug' => 'hat-cowboy',             'name' => 'Cowboy Hoed',          'description' => 'Yeehaw! Tijd om te rodeo-en.',                               'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-cowboy',             'level_required' => 4],
            ['slug' => 'hat-pirate',             'name' => 'Piraten Hoed',         'description' => 'Arrr! Klaar om de zeeën te veroveren.',                      'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-pirate',             'level_required' => 5],
            ['slug' => 'hat-chef',               'name' => 'Koksmuts',             'description' => 'De perfecte look voor een meesterkok.',                      'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-chef',               'level_required' => 3],
            ['slug' => 'hat-top-hat',            'name' => 'Hoge Hoed',            'description' => 'Classy en chic. Pinky omhoog.',                              'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-top-hat',            'level_required' => 4],
            ['slug' => 'hat-detective',          'name' => 'Detective Hoed',       'description' => 'Elementair, mijn beste Watson.',                             'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-detective',          'level_required' => 4],
            ['slug' => 'hat-nurse',              'name' => 'Verpleeger Kapje',     'description' => 'Klaar om te helpen!',                                        'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-nurse',              'level_required' => 3],
            ['slug' => 'hat-graduation',         'name' => 'Afstudeerhoed',        'description' => 'Je hebt het gehaald! Toch?',                                'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-graduation',         'level_required' => 5],
            ['slug' => 'hat-viking',             'name' => 'Viking Helm',          'description' => 'Valhalla wacht! Vikinghelm met hoorns.',                     'type' => 'hat', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'hat-viking',             'level_required' => 5],
            ['slug' => 'hat-mushroom',           'name' => 'Paddenstoel',          'description' => 'Een schattige paddenstoel op je hoofd.',                     'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-mushroom',           'level_required' => 3],
            ['slug' => 'hat-cat-ears',           'name' => 'Kattenoortjes',        'description' => 'Miauw! Schattige kattenoortjes.',                           'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-cat-ears',           'level_required' => 2],
            ['slug' => 'hat-bunny-ears',         'name' => 'Konijnenoortjes',      'description' => 'Hop hop! Pluizige konijnenoortjes.',                        'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-bunny-ears',         'level_required' => 2],
            ['slug' => 'hat-pumpkin',            'name' => 'Pompoen',              'description' => 'Spooky! Een uitgeholde pompoen.',                            'type' => 'hat', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'hat-pumpkin',            'level_required' => 4],
            ['slug' => 'hat-hard-hat',           'name' => 'Bouwhelm',             'description' => 'Veiligheid eerst! Werk in uitvoering.',                      'type' => 'hat', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'hat-hard-hat',           'level_required' => 3],

            // Epic (12)
            ['slug' => 'hat-crown',              'name' => 'Koninklijke Kroon',    'description' => 'Alleen de beste spelers verdienen een kroon.',               'type' => 'hat', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'hat-crown',              'level_required' => 7],
            ['slug' => 'hat-horns',              'name' => 'Duivelshoorns',        'description' => 'Een beetje ondeugend, een beetje cool.',                     'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-horns',              'level_required' => 8],
            ['slug' => 'hat-astronaut',          'name' => 'Astronauten Helm',     'description' => 'Eén kleine stap voor een gamer...',                         'type' => 'hat', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'hat-astronaut',          'level_required' => 10],
            ['slug' => 'hat-samurai',            'name' => 'Samurai Helm',         'description' => 'De eer van de bushido. Japanse krijger.',                    'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-samurai',            'level_required' => 8],
            ['slug' => 'hat-knight',             'name' => 'Ridderhelm',           'description' => 'Bescherm het koninkrijk met eer.',                           'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-knight',             'level_required' => 8],
            ['slug' => 'hat-pharaoh',            'name' => 'Farao Kroon',          'description' => 'Heers over het oude Egypte.',                                'type' => 'hat', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'hat-pharaoh',            'level_required' => 9],
            ['slug' => 'hat-robot',              'name' => 'Robot Hoofd',          'description' => 'Beep boop. Ik ben een robot.',                               'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-robot',              'level_required' => 8],
            ['slug' => 'hat-witch',              'name' => 'Heksenhoed',           'description' => 'Duistere magie en toverspreuken.',                           'type' => 'hat', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'hat-witch',              'level_required' => 7],
            ['slug' => 'hat-pilot',              'name' => 'Piloten Helm',         'description' => 'Klaar voor de vlucht. Mayday mayday!',                      'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-pilot',              'level_required' => 8],
            ['slug' => 'hat-antlers',            'name' => 'Rendiergewei',         'description' => 'Rudolph zou trots zijn.',                                    'type' => 'hat', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'hat-antlers',            'level_required' => 7],
            ['slug' => 'hat-alien',              'name' => 'Alien Antenne',        'description' => 'Buitenaards contact gemaakt!',                               'type' => 'hat', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'hat-alien',              'level_required' => 9],
            ['slug' => 'hat-spartan',            'name' => 'Spartaanse Helm',      'description' => 'Dit is Sparta! Vechten tot het einde.',                     'type' => 'hat', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'hat-spartan',            'level_required' => 10],

            // Legendary (8)
            ['slug' => 'hat-halo',               'name' => 'Heilige Halo',         'description' => 'Een stralende halo voor de meest nobele spelers.',           'type' => 'hat', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'hat-halo',               'level_required' => 15],
            ['slug' => 'hat-dragon-skull',       'name' => 'Draakschedel',         'description' => 'De schedel van een verslagen draak als helm.',               'type' => 'hat', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'hat-dragon-skull',       'level_required' => 16],
            ['slug' => 'hat-flame-crown',        'name' => 'Vlammende Kroon',      'description' => 'Een kroon van puur vuur. Onverslaanbaar.',                  'type' => 'hat', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'hat-flame-crown',        'level_required' => 18],
            ['slug' => 'hat-ice-crown',          'name' => 'IJskroon',             'description' => 'Bevroren perfectie. De Nacht Koning.',                      'type' => 'hat', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'hat-ice-crown',          'level_required' => 16],
            ['slug' => 'hat-galaxy-helmet',      'name' => 'Sterrenstelsel Helm',  'description' => 'Een helm van pure kosmische energie.',                      'type' => 'hat', 'rarity' => 'legendary', 'price' => 650,  'css_class' => 'hat-galaxy-helmet',      'level_required' => 20],
            ['slug' => 'hat-thunder',            'name' => 'Bliksemkroon',         'description' => 'De kracht van de donder op je hoofd.',                      'type' => 'hat', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'hat-thunder',            'level_required' => 15],
            ['slug' => 'hat-shadow-hood',        'name' => 'Schaduw Kap',          'description' => 'Verberg je in de schaduwen. Mysterieus.',                   'type' => 'hat', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'hat-shadow-hood',        'level_required' => 14],
            ['slug' => 'hat-nature-crown',       'name' => 'Natuurkroon',          'description' => 'Een levende kroon van wortels en bladeren.',                'type' => 'hat', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'hat-nature-crown',       'level_required' => 14],

            // ════════════════════════════════════════════════════════════════
            // ── EFFECTS (50) ─────────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════

            // Common (12)
            ['slug' => 'effect-confetti',        'name' => 'Confetti',             'description' => 'Feestelijke confetti rond je avatar.',                       'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-confetti',        'level_required' => 0],
            ['slug' => 'effect-bubbles',         'name' => 'Bubbels',              'description' => 'Vrolijke zeepbellen stijgen op.',                            'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-bubbles',         'level_required' => 0],
            ['slug' => 'effect-dots',            'name' => 'Stipjes',              'description' => 'Kleine gekleurde stipjes zweven rond.',                      'type' => 'effect', 'rarity' => 'common',    'price' => 50,   'css_class' => 'effect-dots',            'level_required' => 0],
            ['slug' => 'effect-leaves',          'name' => 'Vallende Blaadjes',    'description' => 'Herfstbladeren dwarrelen omlaag.',                           'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-leaves',          'level_required' => 0],
            ['slug' => 'effect-petals',          'name' => 'Bloemblaadjes',        'description' => 'Zachte roze bloemblaadjes waaien rond.',                     'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-petals',          'level_required' => 0],
            ['slug' => 'effect-rain',            'name' => 'Regendruppels',        'description' => 'Zachte regen valt rond je avatar.',                          'type' => 'effect', 'rarity' => 'common',    'price' => 50,   'css_class' => 'effect-rain',            'level_required' => 0],
            ['slug' => 'effect-dust',            'name' => 'Stofdeeltjes',         'description' => 'Zwevende stofjes in het zonlicht.',                          'type' => 'effect', 'rarity' => 'common',    'price' => 50,   'css_class' => 'effect-dust',            'level_required' => 0],
            ['slug' => 'effect-music-notes',     'name' => 'Muzieknoten',          'description' => 'Noten dansen rond je hoofd.',                                'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-music-notes',     'level_required' => 0],
            ['slug' => 'effect-feathers',        'name' => 'Veertjes',             'description' => 'Lichte veertjes zweven voorbij.',                            'type' => 'effect', 'rarity' => 'common',    'price' => 50,   'css_class' => 'effect-feathers',        'level_required' => 0],
            ['slug' => 'effect-twinkle',         'name' => 'Twinkeling',           'description' => 'Zacht twinkelend licht.',                                    'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-twinkle',         'level_required' => 0],
            ['slug' => 'effect-wind',            'name' => 'Windvlaag',            'description' => 'Een zachte bries waait langs je avatar.',                    'type' => 'effect', 'rarity' => 'common',    'price' => 50,   'css_class' => 'effect-wind',            'level_required' => 0],
            ['slug' => 'effect-dandelion',       'name' => 'Paardenbloem',         'description' => 'Pluisjes waaien weg in de wind.',                            'type' => 'effect', 'rarity' => 'common',    'price' => 60,   'css_class' => 'effect-dandelion',       'level_required' => 0],

            // Rare (15)
            ['slug' => 'effect-sparkle',         'name' => 'Sparkles',             'description' => 'Glinsterende sterretjes rond je profiel.',                   'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-sparkle',         'level_required' => 3],
            ['slug' => 'effect-hearts',          'name' => 'Hartjes',              'description' => 'Zwevende hartjes rond je avatar.',                           'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-hearts',          'level_required' => 3],
            ['slug' => 'effect-snowflakes',      'name' => 'Sneeuwvlokken',        'description' => 'Zachte sneeuwvlokjes dwarrelen rond je heen.',              'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-snowflakes',      'level_required' => 4],
            ['slug' => 'effect-stars',           'name' => 'Sterren',              'description' => 'Gouden sterren draaien rond je avatar.',                     'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-stars',           'level_required' => 3],
            ['slug' => 'effect-cherry-blossom',  'name' => 'Kersenbloesem',        'description' => 'Japanse kersenbloesems dalen neer.',                        'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-cherry-blossom',  'level_required' => 4],
            ['slug' => 'effect-butterflies',     'name' => 'Vlinders',             'description' => 'Kleurrijke vlinders fladderen rond.',                       'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-butterflies',     'level_required' => 4],
            ['slug' => 'effect-fireflies',       'name' => 'Vuurvliegjes',         'description' => 'Gloeiiende vuurvliegjes in de schemering.',                 'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-fireflies',       'level_required' => 5],
            ['slug' => 'effect-diamonds',        'name' => 'Diamantjes',           'description' => 'Kleine diamantjes glinsteren rond je.',                     'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-diamonds',        'level_required' => 5],
            ['slug' => 'effect-coins',           'name' => 'Vallende Coins',       'description' => 'Gouden munten regenen neer. Ka-ching!',                     'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-coins',           'level_required' => 3],
            ['slug' => 'effect-embers',          'name' => 'Sintels',              'description' => 'Gloeiende sintels stijgen langzaam op.',                     'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-embers',          'level_required' => 4],
            ['slug' => 'effect-sakura',          'name' => 'Sakura',               'description' => 'Roze sakurabloesem waait in de wind.',                      'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-sakura',          'level_required' => 4],
            ['slug' => 'effect-lightning-bugs',  'name' => 'Lichtflitsen',         'description' => 'Kleine lichtflitsjes knipperen rond je.',                   'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-lightning-bugs',  'level_required' => 3],
            ['slug' => 'effect-crystals',        'name' => 'Kristallen',           'description' => 'Schitterende kristallen zweven in de lucht.',               'type' => 'effect', 'rarity' => 'rare',      'price' => 175,  'css_class' => 'effect-crystals',        'level_required' => 5],
            ['slug' => 'effect-pixel-dust',      'name' => 'Pixel Stof',           'description' => 'Retro pixeldeeltjes schieten rond.',                        'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-pixel-dust',      'level_required' => 3],
            ['slug' => 'effect-soap-bubbles',    'name' => 'Zeepbellen',           'description' => 'Grote regenboog zeepbellen stijgen op.',                    'type' => 'effect', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'effect-soap-bubbles',    'level_required' => 3],

            // Epic (14)
            ['slug' => 'effect-rainbow',         'name' => 'Regenboog Gloed',      'description' => 'Een subtiele regenboog animatie rond je avatar.',            'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-rainbow',         'level_required' => 8],
            ['slug' => 'effect-fire-ring',       'name' => 'Vuurring',             'description' => 'Vlammen dansen rond je avatar.',                             'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-fire-ring',       'level_required' => 9],
            ['slug' => 'effect-electric-arc',    'name' => 'Bliksemschicht',       'description' => 'Elektrische vonken schieten rond je avatar.',                'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-electric-arc',    'level_required' => 10],
            ['slug' => 'effect-ice-shards',      'name' => 'IJsscherven',          'description' => 'Scherpe ijskristallen zweven rond je.',                     'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-ice-shards',      'level_required' => 8],
            ['slug' => 'effect-toxic-cloud',     'name' => 'Gifwolk',              'description' => 'Een gifgroene nevel omhult je avatar.',                      'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-toxic-cloud',     'level_required' => 8],
            ['slug' => 'effect-blood-drip',      'name' => 'Bloeddruppels',        'description' => 'Duistere rode druppels. Halloween vibes.',                   'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-blood-drip',      'level_required' => 9],
            ['slug' => 'effect-golden-aura',     'name' => 'Gouden Aura',          'description' => 'Een stralende gouden aura van kracht.',                      'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-golden-aura',     'level_required' => 9],
            ['slug' => 'effect-neon-rings',      'name' => 'Neon Ringen',          'description' => 'Draaiende neon ringen rond je profiel.',                     'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-neon-rings',      'level_required' => 8],
            ['slug' => 'effect-plasma-orbs',     'name' => 'Plasma Bollen',        'description' => 'Zwevende bollen van pure plasma energie.',                   'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-plasma-orbs',     'level_required' => 10],
            ['slug' => 'effect-spirit-wisps',    'name' => 'Geestenvlammen',       'description' => 'Spookachtige blauwe vlammetjes zweven rond.',                'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-spirit-wisps',    'level_required' => 8],
            ['slug' => 'effect-matrix',          'name' => 'Matrix Code',          'description' => 'Groene code valt als regen. Wake up Neo.',                   'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-matrix',          'level_required' => 9],
            ['slug' => 'effect-cherry-flames',   'name' => 'Roze Vlammen',         'description' => 'Zachte roze vlammen. Mooi en dodelijk.',                     'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-cherry-flames',   'level_required' => 8],
            ['slug' => 'effect-rune-circle',     'name' => 'Runen Cirkel',         'description' => 'Mystieke runen draaien rond je avatar.',                     'type' => 'effect', 'rarity' => 'epic',      'price' => 325,  'css_class' => 'effect-rune-circle',     'level_required' => 10],
            ['slug' => 'effect-sonic-waves',     'name' => 'Geluidsgolven',        'description' => 'Pulerende geluidsgolven rond je profiel.',                   'type' => 'effect', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'effect-sonic-waves',     'level_required' => 8],

            // Legendary (9)
            ['slug' => 'effect-galaxy',          'name' => 'Melkweg',              'description' => 'Een draaiende galaxy rond je profiel. Episch.',               'type' => 'effect', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'effect-galaxy',          'level_required' => 15],
            ['slug' => 'effect-shadow-aura',     'name' => 'Schaduw Aura',         'description' => 'Een mysterieuze donkere aura omhult je avatar.',             'type' => 'effect', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'effect-shadow-aura',     'level_required' => 18],
            ['slug' => 'effect-phoenix',         'name' => 'Feniks Vlammen',       'description' => 'Herrijzen uit de as met vuur en glorie.',                    'type' => 'effect', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'effect-phoenix',         'level_required' => 20],
            ['slug' => 'effect-black-hole',      'name' => 'Zwart Gat',            'description' => 'Een mini zwart gat zuigt licht op rond je.',                 'type' => 'effect', 'rarity' => 'legendary', 'price' => 650,  'css_class' => 'effect-black-hole',      'level_required' => 20],
            ['slug' => 'effect-aurora-borealis', 'name' => 'Noorderlicht',         'description' => 'Het prachtige noorderlicht danst rond je.',                  'type' => 'effect', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'effect-aurora-borealis', 'level_required' => 16],
            ['slug' => 'effect-dragon-fire',     'name' => 'Drakenvuur',           'description' => 'Vlammen van een oude draak omhullen je.',                    'type' => 'effect', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'effect-dragon-fire',     'level_required' => 18],
            ['slug' => 'effect-void-rift',       'name' => 'Void Scheur',          'description' => 'Een scheur in de ruimtetijd rond je avatar.',                'type' => 'effect', 'rarity' => 'legendary', 'price' => 650,  'css_class' => 'effect-void-rift',       'level_required' => 20],
            ['slug' => 'effect-celestial',       'name' => 'Hemels Licht',         'description' => 'Goddelijk licht straalt van boven op je neer.',              'type' => 'effect', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'effect-celestial',       'level_required' => 16],
            ['slug' => 'effect-supernova-burst', 'name' => 'Supernova Burst',      'description' => 'Een kosmische explosie van licht en energie.',               'type' => 'effect', 'rarity' => 'legendary', 'price' => 700,  'css_class' => 'effect-supernova-burst', 'level_required' => 22],

            // ════════════════════════════════════════════════════════════════
            // ── BADGE FLAIRS (50) ────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════

            // Common (15)
            ['slug' => 'flair-noob',             'name' => 'Noob',                 'description' => 'We beginnen allemaal ergens. Draag het met trots.',           'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-noob',             'level_required' => 0],
            ['slug' => 'flair-oeps',             'name' => 'Oeps',                 'description' => 'Voor als het weer eens mis gaat.',                            'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-oeps',             'level_required' => 0],
            ['slug' => 'flair-zzz',              'name' => 'ZzZzZ',                'description' => 'AFK koning. Altijd aan het slapen.',                          'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-zzz',              'level_required' => 0],
            ['slug' => 'flair-sus',              'name' => 'Sus',                  'description' => 'Beetje verdacht allemaal...',                                 'type' => 'badge_flair', 'rarity' => 'common',    'price' => 50,   'css_class' => 'flair-sus',              'level_required' => 0],
            ['slug' => 'flair-lol',              'name' => 'LOL',                  'description' => 'Altijd aan het lachen.',                                      'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-lol',              'level_required' => 0],
            ['slug' => 'flair-brb',              'name' => 'BRB',                  'description' => 'Ben zo terug! Waarschijnlijk.',                               'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-brb',              'level_required' => 0],
            ['slug' => 'flair-yolo',             'name' => 'YOLO',                 'description' => 'Je leeft maar één keer. Toch?',                              'type' => 'badge_flair', 'rarity' => 'common',    'price' => 50,   'css_class' => 'flair-yolo',             'level_required' => 0],
            ['slug' => 'flair-rip',              'name' => 'RIP',                  'description' => 'Rust in vrede, je score.',                                    'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-rip',              'level_required' => 0],
            ['slug' => 'flair-help',             'name' => 'HELP',                 'description' => 'Ik heb geen idee wat ik doe.',                                'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-help',             'level_required' => 0],
            ['slug' => 'flair-meh',              'name' => 'Meh',                  'description' => 'Niet enthousiast, niet teleurgesteld.',                       'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-meh',              'level_required' => 0],
            ['slug' => 'flair-omg',              'name' => 'OMG',                  'description' => 'Oh mijn god! Elke keer weer.',                                'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-omg',              'level_required' => 0],
            ['slug' => 'flair-nerd',             'name' => 'Nerd',                 'description' => 'En daar ben ik trots op.',                                    'type' => 'badge_flair', 'rarity' => 'common',    'price' => 50,   'css_class' => 'flair-nerd',             'level_required' => 0],
            ['slug' => 'flair-chill',            'name' => 'Chill',                'description' => 'Relax, het is maar een game.',                                'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-chill',            'level_required' => 0],
            ['slug' => 'flair-newbie',           'name' => 'Newbie',               'description' => 'Vers van de pers. Iedereen begint klein.',                    'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-newbie',           'level_required' => 0],
            ['slug' => 'flair-afk',              'name' => 'AFK',                  'description' => 'Away from keyboard. Altijd.',                                 'type' => 'badge_flair', 'rarity' => 'common',    'price' => 25,   'css_class' => 'flair-afk',              'level_required' => 0],

            // Rare (15)
            ['slug' => 'flair-skill-issue',      'name' => 'Skill Issue',          'description' => 'Git gud. Of niet. Whatever.',                                 'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-skill-issue',      'level_required' => 2],
            ['slug' => 'flair-tryhard',          'name' => 'Tryhard',              'description' => 'Je probeert te hard. En het werkt.',                          'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-tryhard',          'level_required' => 3],
            ['slug' => 'flair-touch-grass',      'name' => 'Touch Grass',          'description' => 'Misschien is het tijd om even naar buiten te gaan.',          'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-touch-grass',      'level_required' => 4],
            ['slug' => 'flair-gg-ez',            'name' => 'GG EZ',                'description' => 'Was niet eens moeilijk.',                                     'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-gg-ez',            'level_required' => 3],
            ['slug' => 'flair-carried',          'name' => 'Carried',              'description' => 'Je hoefde niks te doen. Bedank je team.',                     'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-carried',          'level_required' => 2],
            ['slug' => 'flair-rage-quit',        'name' => 'Rage Quit',            'description' => 'Alt+F4 is ook een oplossing.',                                'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-rage-quit',        'level_required' => 2],
            ['slug' => 'flair-no-cap',           'name' => 'No Cap',               'description' => 'Echt waar. Geen leugens.',                                    'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-no-cap',           'level_required' => 2],
            ['slug' => 'flair-clutch',           'name' => 'Clutch',               'description' => 'Altijd op het laatste moment redden.',                        'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-clutch',           'level_required' => 4],
            ['slug' => 'flair-based',            'name' => 'Based',                'description' => 'Gebaseerd en roodgepild.',                                    'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-based',            'level_required' => 3],
            ['slug' => 'flair-w',                'name' => 'W',                    'description' => 'Alleen maar wins. Nooit losses.',                             'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-w',                'level_required' => 2],
            ['slug' => 'flair-l',                'name' => 'L',                    'description' => 'Soms verlies je. Vaak, eigenlijk.',                           'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-l',                'level_required' => 2],
            ['slug' => 'flair-toxic',            'name' => 'Toxic',                'description' => 'Giftig maar eerlijk.',                                        'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-toxic',            'level_required' => 3],
            ['slug' => 'flair-og',               'name' => 'OG',                   'description' => 'Original gangster. Vanaf dag één.',                           'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-og',               'level_required' => 4],
            ['slug' => 'flair-beta',             'name' => 'Beta Tester',          'description' => 'Was er voordat het cool was.',                                 'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'flair-beta',             'level_required' => 4],
            ['slug' => 'flair-salty',            'name' => 'Salty',                'description' => 'Een beetje zout. Oké, heel zout.',                             'type' => 'badge_flair', 'rarity' => 'rare',      'price' => 100,  'css_class' => 'flair-salty',            'level_required' => 2],

            // Epic (12)
            ['slug' => 'flair-big-brain',        'name' => 'Big Brain',            'description' => '200 IQ plays. Elke keer.',                                    'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 200,  'css_class' => 'flair-big-brain',        'level_required' => 7],
            ['slug' => 'flair-geen-leven',       'name' => 'Geen Leven',           'description' => 'Je bent hier WAY te vaak. Respect.',                          'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'flair-geen-leven',       'level_required' => 8],
            ['slug' => 'flair-speedrunner',      'name' => 'Speedrunner',          'description' => 'Sneller dan je scherm kan bijhouden.',                        'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'flair-speedrunner',      'level_required' => 10],
            ['slug' => 'flair-1iq',              'name' => '1 IQ',                 'description' => 'Het is een vibe. Geen brainpower nodig.',                     'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 200,  'css_class' => 'flair-1iq',              'level_required' => 6],
            ['slug' => 'flair-built-different',  'name' => 'Built Different',      'description' => 'Niet zoals de rest. Anders gebouwd.',                         'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'flair-built-different',  'level_required' => 8],
            ['slug' => 'flair-main-character',   'name' => 'Main Character',       'description' => 'De wereld draait om jou. Letterlijk.',                        'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'flair-main-character',   'level_required' => 9],
            ['slug' => 'flair-sigma',            'name' => 'Sigma',                'description' => 'Op je sigma grindset. Lone wolf.',                            'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'flair-sigma',            'level_required' => 7],
            ['slug' => 'flair-galaxy-brain',     'name' => 'Galaxy Brain',         'description' => 'Je brein bevat hele sterrenstelsels.',                         'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'flair-galaxy-brain',     'level_required' => 10],
            ['slug' => 'flair-menace',           'name' => 'Menace',               'description' => 'Een gevaar voor de samenleving.',                              'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 225,  'css_class' => 'flair-menace',           'level_required' => 8],
            ['slug' => 'flair-npc',              'name' => 'NPC',                  'description' => 'Herhaal dezelfde zin. Elke dag.',                              'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 200,  'css_class' => 'flair-npc',              'level_required' => 6],
            ['slug' => 'flair-goated',           'name' => 'Goated',               'description' => 'Met de saus. Absoluut goated.',                                'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'flair-goated',           'level_required' => 9],
            ['slug' => 'flair-final-boss',       'name' => 'Final Boss',           'description' => 'Het laatste obstakel. Succes ermee.',                          'type' => 'badge_flair', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'flair-final-boss',       'level_required' => 10],

            // Legendary (8)
            ['slug' => 'flair-custom-gold',      'name' => 'Custom Badge',         'description' => 'Kies je eigen tekst, icon en kleur!',                         'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 750,  'css_class' => 'flair-custom-gold',      'level_required' => 25],
            ['slug' => 'flair-custom-rainbow',   'name' => 'Gradient Badge',       'description' => 'Kies je eigen tekst, icon en 3 kleuren! Premium versie.',     'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 1000, 'css_class' => 'flair-custom-rainbow',   'level_required' => 30],
            ['slug' => 'flair-goat',             'name' => 'G.O.A.T.',             'description' => 'Greatest Of All Time. Punt.',                                  'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'flair-goat',             'level_required' => 12],
            ['slug' => 'flair-legendary',        'name' => 'Legendary',            'description' => 'Je bent een legende. Geen discussie.',                         'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'flair-legendary',        'level_required' => 14],
            ['slug' => 'flair-god-mode',         'name' => 'God Mode',             'description' => 'Onverslaanbaar. Onsterfelijk. God Mode.',                      'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'flair-god-mode',         'level_required' => 16],
            ['slug' => 'flair-prestige',         'name' => 'Prestige',             'description' => 'Het hoogste niveau van aanzien.',                              'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'flair-prestige',         'level_required' => 14],
            ['slug' => 'flair-mythic',           'name' => 'Mythisch',             'description' => 'Verhalen worden over jou verteld.',                            'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'flair-mythic',           'level_required' => 18],
            ['slug' => 'flair-gg-wp',            'name' => 'GG WP',                'description' => 'Good game, well played. De ultieme eer.',                      'type' => 'badge_flair', 'rarity' => 'legendary', 'price' => 450,  'css_class' => 'flair-gg-wp',            'level_required' => 12],

            // ════════════════════════════════════════════════════════════════
            // ── NAME COLORS (50) ─────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════

            // Common (15)
            ['slug' => 'name-red',               'name' => 'Rode Naam',            'description' => 'Je naam wordt rood weergegeven.',                            'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-red-500',                                                                'level_required' => 0],
            ['slug' => 'name-blue',              'name' => 'Blauwe Naam',          'description' => 'Een klassieke blauwe naam.',                                 'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-blue-500',                                                               'level_required' => 0],
            ['slug' => 'name-green',             'name' => 'Groene Naam',          'description' => 'Fris groen als de natuur.',                                  'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-emerald-500',                                                            'level_required' => 0],
            ['slug' => 'name-orange',            'name' => 'Oranje Naam',          'description' => 'Warm oranje als een zonsondergang.',                         'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-orange-500',                                                             'level_required' => 0],
            ['slug' => 'name-purple',            'name' => 'Paarse Naam',          'description' => 'Koninklijk paars voor echte royalty.',                        'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-purple-500',                                                             'level_required' => 0],
            ['slug' => 'name-yellow',            'name' => 'Gele Naam',            'description' => 'Stralend geel als de zon.',                                  'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-yellow-500',                                                             'level_required' => 0],
            ['slug' => 'name-cyan',              'name' => 'Cyaan Naam',           'description' => 'Koel en fris als ijswater.',                                 'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-cyan-500',                                                               'level_required' => 0],
            ['slug' => 'name-indigo',            'name' => 'Indigo Naam',          'description' => 'Diep en mysterieus indigo.',                                 'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-indigo-500',                                                             'level_required' => 0],
            ['slug' => 'name-lime',              'name' => 'Limoengroen Naam',     'description' => 'Fris limoengroen dat opvalt.',                               'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-lime-500',                                                               'level_required' => 0],
            ['slug' => 'name-rose',              'name' => 'Rozé Naam',            'description' => 'Elegant rozé, zacht maar stijlvol.',                         'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-rose-500',                                                               'level_required' => 0],
            ['slug' => 'name-amber',             'name' => 'Amber Naam',           'description' => 'Warme amber tinten.',                                        'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-amber-500',                                                              'level_required' => 0],
            ['slug' => 'name-slate',             'name' => 'Leistenen Naam',       'description' => 'Koel grijs met karakter.',                                   'type' => 'name_color', 'rarity' => 'common',    'price' => 50,   'css_class' => 'text-slate-500',                                                              'level_required' => 0],
            ['slug' => 'name-sky',               'name' => 'Hemelsblauwe Naam',    'description' => 'Licht als de hemel op een mooie dag.',                       'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-sky-500',                                                                'level_required' => 0],
            ['slug' => 'name-fuchsia',           'name' => 'Fuchsia Naam',         'description' => 'Bold en onvergetelijk fuchsia.',                             'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-fuchsia-500',                                                            'level_required' => 0],
            ['slug' => 'name-violet',            'name' => 'Violet Naam',          'description' => 'Zacht violet met een vleugje magie.',                        'type' => 'name_color', 'rarity' => 'common',    'price' => 75,   'css_class' => 'text-violet-500',                                                             'level_required' => 0],

            // Rare (12)
            ['slug' => 'name-pink',              'name' => 'Roze Naam',            'description' => 'Opvallend roze. Girl power.',                                'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-pink-500',                                                               'level_required' => 3],
            ['slug' => 'name-teal',              'name' => 'Teal Naam',            'description' => 'Rustig en verfijnd.',                                        'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-teal-500',                                                               'level_required' => 3],
            ['slug' => 'name-dark-red',          'name' => 'Donkerrode Naam',      'description' => 'Diep rood als rode wijn.',                                   'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-red-700',                                                                'level_required' => 3],
            ['slug' => 'name-dark-blue',         'name' => 'Donkerblauwe Naam',    'description' => 'Diep blauw als de oceaan bij nacht.',                        'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-blue-700',                                                               'level_required' => 3],
            ['slug' => 'name-emerald',           'name' => 'Smaragden Naam',       'description' => 'Rijk smaragdgroen als een edelsteen.',                       'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-emerald-600',                                                            'level_required' => 4],
            ['slug' => 'name-gold',              'name' => 'Gouden Naam',          'description' => 'Glanzend goud. Eerste klas.',                                'type' => 'name_color', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'text-yellow-600',                                                             'level_required' => 5],
            ['slug' => 'name-coral',             'name' => 'Koraal Naam',          'description' => 'Warm koraalrood als een tropisch rif.',                      'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-rose-400',                                                               'level_required' => 3],
            ['slug' => 'name-crimson',           'name' => 'Karmozijn Naam',       'description' => 'Intens karmozijnrood. Passie en kracht.',                    'type' => 'name_color', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'text-red-600',                                                                'level_required' => 5],
            ['slug' => 'name-forest',            'name' => 'Bosgroene Naam',       'description' => 'Donkergroen als een diep bos.',                              'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-green-700',                                                              'level_required' => 4],
            ['slug' => 'name-royal-blue',        'name' => 'Koningsblauw Naam',    'description' => 'Het blauw van de koninklijke garde.',                        'type' => 'name_color', 'rarity' => 'rare',      'price' => 150,  'css_class' => 'text-blue-600',                                                               'level_required' => 5],
            ['slug' => 'name-bronze',            'name' => 'Bronzen Naam',         'description' => 'Derde plek is ook een plek.',                                'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-amber-700',                                                              'level_required' => 3],
            ['slug' => 'name-deep-purple',       'name' => 'Dieppaarse Naam',      'description' => 'Mysterieus diep paars.',                                    'type' => 'name_color', 'rarity' => 'rare',      'price' => 125,  'css_class' => 'text-purple-700',                                                             'level_required' => 4],

            // Epic (14) — gradients & animated
            ['slug' => 'name-gradient',          'name' => 'Gradient Naam',        'description' => 'Je naam krijgt een mooie kleurovergang.',                    'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-purple-500 to-pink-500 bg-clip-text text-transparent',   'level_required' => 6],
            ['slug' => 'name-sunset',            'name' => 'Zonsondergang',        'description' => 'Warme kleuren van goud naar rood.',                          'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-amber-500 to-red-500 bg-clip-text text-transparent',    'level_required' => 8],
            ['slug' => 'name-ocean',             'name' => 'Oceaan Gradient',      'description' => 'Van diepzeeblauw tot turquoise.',                            'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-blue-600 to-cyan-400 bg-clip-text text-transparent',    'level_required' => 8],
            ['slug' => 'name-neon-pulse',        'name' => 'Neon Pulse',           'description' => 'Je naam pulseert met een neon gloed.',                       'type' => 'name_color', 'rarity' => 'epic',      'price' => 300,  'css_class' => 'animate-name-neon-pulse',                                                     'level_required' => 9],
            ['slug' => 'name-forest-gradient',   'name' => 'Bos Gradient',         'description' => 'Van donkergroen naar lentegroen.',                           'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-green-700 to-emerald-400 bg-clip-text text-transparent', 'level_required' => 7],
            ['slug' => 'name-berry',             'name' => 'Bessen Gradient',      'description' => 'Van diep paars naar roze als wilde bessen.',                 'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-purple-700 to-rose-400 bg-clip-text text-transparent',  'level_required' => 7],
            ['slug' => 'name-toxic-gradient',    'name' => 'Giftig Gradient',      'description' => 'Radioactief groen naar geel. Pas op!',                      'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-lime-500 to-yellow-400 bg-clip-text text-transparent',  'level_required' => 8],
            ['slug' => 'name-cotton-candy',      'name' => 'Suikerspin',           'description' => 'Zoet roze naar lichtblauw als suikerspin.',                  'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-pink-400 to-sky-400 bg-clip-text text-transparent',     'level_required' => 7],
            ['slug' => 'name-lava',              'name' => 'Lava Gradient',        'description' => 'Gloeiend van rood naar oranje als lava.',                    'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-red-600 to-orange-400 bg-clip-text text-transparent',   'level_required' => 8],
            ['slug' => 'name-ice',               'name' => 'IJs Gradient',         'description' => 'Van ijsblauw naar wit. Bevroren schoonheid.',                'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-blue-400 to-cyan-200 bg-clip-text text-transparent',    'level_required' => 7],
            ['slug' => 'name-midnight',          'name' => 'Middernacht',          'description' => 'Donker indigo naar paars als de nachtlucht.',                'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-indigo-700 to-violet-500 bg-clip-text text-transparent', 'level_required' => 8],
            ['slug' => 'name-gold-gradient',     'name' => 'Gouden Gradient',      'description' => 'Van goud naar bronskleurig. Luxe.',                         'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-yellow-400 to-amber-600 bg-clip-text text-transparent', 'level_required' => 8],
            ['slug' => 'name-electric-blue',     'name' => 'Elektrisch Blauw',     'description' => 'Van felblauw naar cyan. Geladen.',                           'type' => 'name_color', 'rarity' => 'epic',      'price' => 250,  'css_class' => 'bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-transparent',    'level_required' => 7],
            ['slug' => 'name-rose-gold',         'name' => 'Rosé Goud',            'description' => 'Elegante rosé goud tinten.',                                 'type' => 'name_color', 'rarity' => 'epic',      'price' => 275,  'css_class' => 'bg-gradient-to-r from-rose-400 to-amber-300 bg-clip-text text-transparent',   'level_required' => 8],

            // Legendary (9) — animated & premium gradients
            ['slug' => 'name-aurora',            'name' => 'Noorderlicht',         'description' => 'Je naam schittert als het noorderlicht.',                    'type' => 'name_color', 'rarity' => 'legendary', 'price' => 450,  'css_class' => 'bg-gradient-to-r from-green-400 via-cyan-400 to-purple-500 bg-clip-text text-transparent', 'level_required' => 12],
            ['slug' => 'name-rainbow',           'name' => 'Regenboog Naam',       'description' => 'Je naam verandert continu van kleur. Maximale flex.',        'type' => 'name_color', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'animate-name-rainbow',                                                        'level_required' => 15],
            ['slug' => 'name-fire',              'name' => 'Vuur Naam',            'description' => 'Vlammen dansen door je naam. Heet!',                         'type' => 'name_color', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'animate-name-fire',                                                           'level_required' => 14],
            ['slug' => 'name-glitch',            'name' => 'Glitch Naam',          'description' => 'Je naam glitcht als een hackerman.',                         'type' => 'name_color', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'animate-name-glitch',                                                         'level_required' => 18],
            ['slug' => 'name-galaxy',            'name' => 'Galaxy Naam',          'description' => 'Je naam bevat een heel sterrenstelsel.',                     'type' => 'name_color', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500 bg-clip-text text-transparent', 'level_required' => 16],
            ['slug' => 'name-plasma',            'name' => 'Plasma Naam',          'description' => 'Pure energie stroomt door je naam.',                         'type' => 'name_color', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'bg-gradient-to-r from-violet-500 via-fuchsia-500 to-pink-500 bg-clip-text text-transparent', 'level_required' => 14],
            ['slug' => 'name-phoenix',           'name' => 'Feniks Naam',          'description' => 'Je naam herrijst in vlammend goud.',                         'type' => 'name_color', 'rarity' => 'legendary', 'price' => 550,  'css_class' => 'bg-gradient-to-r from-red-500 via-orange-400 to-yellow-300 bg-clip-text text-transparent', 'level_required' => 16],
            ['slug' => 'name-void',              'name' => 'Void Naam',            'description' => 'Donker als de leegte. Niets ontsnapt.',                      'type' => 'name_color', 'rarity' => 'legendary', 'price' => 500,  'css_class' => 'bg-gradient-to-r from-gray-900 via-purple-900 to-gray-900 bg-clip-text text-transparent', 'level_required' => 14],
            ['slug' => 'name-diamond',           'name' => 'Diamant Naam',         'description' => 'Je naam schittert als een geslepen diamant.',                'type' => 'name_color', 'rarity' => 'legendary', 'price' => 600,  'css_class' => 'bg-gradient-to-r from-cyan-300 via-white to-cyan-300 bg-clip-text text-transparent', 'level_required' => 18],

            // ════════════════════════════════════════════════════════════════
            // ── FLAGS ───────────────────────────────────────────────────────
            // ════════════════════════════════════════════════════════════════
            ['slug' => 'flag-nl', 'name' => 'Nederland', 'description' => 'De Nederlandse driekleur.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇳🇱', 'level_required' => 0],
            ['slug' => 'flag-be', 'name' => 'België', 'description' => 'De Belgische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇧🇪', 'level_required' => 0],
            ['slug' => 'flag-de', 'name' => 'Duitsland', 'description' => 'De Duitse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇩🇪', 'level_required' => 0],
            ['slug' => 'flag-fr', 'name' => 'Frankrijk', 'description' => 'De Franse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇫🇷', 'level_required' => 0],
            ['slug' => 'flag-gb', 'name' => 'Verenigd Koninkrijk', 'description' => 'De Britse Union Jack.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇬🇧', 'level_required' => 0],
            ['slug' => 'flag-us', 'name' => 'Verenigde Staten', 'description' => 'Stars and Stripes.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇺🇸', 'level_required' => 0],
            ['slug' => 'flag-es', 'name' => 'Spanje', 'description' => 'De Spaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇪🇸', 'level_required' => 0],
            ['slug' => 'flag-it', 'name' => 'Italië', 'description' => 'Il Tricolore.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇹', 'level_required' => 0],
            ['slug' => 'flag-pt', 'name' => 'Portugal', 'description' => 'De Portugese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇹', 'level_required' => 0],
            ['slug' => 'flag-br', 'name' => 'Brazilië', 'description' => 'Ordem e Progresso.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇧🇷', 'level_required' => 0],
            ['slug' => 'flag-ar', 'name' => 'Argentinië', 'description' => 'De Argentijnse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇷', 'level_required' => 0],
            ['slug' => 'flag-mx', 'name' => 'Mexico', 'description' => 'De Mexicaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇲🇽', 'level_required' => 0],
            ['slug' => 'flag-ca', 'name' => 'Canada', 'description' => 'Het esdoornblad.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇦', 'level_required' => 0],
            ['slug' => 'flag-au', 'name' => 'Australië', 'description' => 'De Australische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇺', 'level_required' => 0],
            ['slug' => 'flag-jp', 'name' => 'Japan', 'description' => 'De Japanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇯🇵', 'level_required' => 0],
            ['slug' => 'flag-kr', 'name' => 'Zuid-Korea', 'description' => 'De Zuid-Koreaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇰🇷', 'level_required' => 0],
            ['slug' => 'flag-cn', 'name' => 'China', 'description' => 'De Chinese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇳', 'level_required' => 0],
            ['slug' => 'flag-in', 'name' => 'India', 'description' => 'De Indiase vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇳', 'level_required' => 0],
            ['slug' => 'flag-ru', 'name' => 'Rusland', 'description' => 'De Russische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇷🇺', 'level_required' => 0],
            ['slug' => 'flag-tr', 'name' => 'Turkije', 'description' => 'De Turkse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇹🇷', 'level_required' => 0],
            ['slug' => 'flag-pl', 'name' => 'Polen', 'description' => 'De Poolse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇱', 'level_required' => 0],
            ['slug' => 'flag-se', 'name' => 'Zweden', 'description' => 'De Zweedse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇪', 'level_required' => 0],
            ['slug' => 'flag-no', 'name' => 'Noorwegen', 'description' => 'De Noorse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇳🇴', 'level_required' => 0],
            ['slug' => 'flag-dk', 'name' => 'Denemarken', 'description' => 'De Deense vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇩🇰', 'level_required' => 0],
            ['slug' => 'flag-fi', 'name' => 'Finland', 'description' => 'De Finse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇫🇮', 'level_required' => 0],
            ['slug' => 'flag-ch', 'name' => 'Zwitserland', 'description' => 'De Zwitserse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇭', 'level_required' => 0],
            ['slug' => 'flag-at', 'name' => 'Oostenrijk', 'description' => 'De Oostenrijkse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇹', 'level_required' => 0],
            ['slug' => 'flag-ie', 'name' => 'Ierland', 'description' => 'De Ierse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇪', 'level_required' => 0],
            ['slug' => 'flag-gr', 'name' => 'Griekenland', 'description' => 'De Griekse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇬🇷', 'level_required' => 0],
            ['slug' => 'flag-cz', 'name' => 'Tsjechië', 'description' => 'De Tsjechische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇿', 'level_required' => 0],
            ['slug' => 'flag-ro', 'name' => 'Roemenië', 'description' => 'De Roemeense vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇷🇴', 'level_required' => 0],
            ['slug' => 'flag-hu', 'name' => 'Hongarije', 'description' => 'De Hongaarse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇭🇺', 'level_required' => 0],
            ['slug' => 'flag-bg', 'name' => 'Bulgarije', 'description' => 'De Bulgaarse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇧🇬', 'level_required' => 0],
            ['slug' => 'flag-hr', 'name' => 'Kroatië', 'description' => 'De Kroatische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇭🇷', 'level_required' => 0],
            ['slug' => 'flag-sk', 'name' => 'Slowakije', 'description' => 'De Slowaakse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇰', 'level_required' => 0],
            ['slug' => 'flag-si', 'name' => 'Slovenië', 'description' => 'De Sloveense vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇮', 'level_required' => 0],
            ['slug' => 'flag-rs', 'name' => 'Servië', 'description' => 'De Servische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇷🇸', 'level_required' => 0],
            ['slug' => 'flag-ua', 'name' => 'Oekraïne', 'description' => 'De Oekraïense vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇺🇦', 'level_required' => 0],
            ['slug' => 'flag-eg', 'name' => 'Egypte', 'description' => 'De Egyptische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇪🇬', 'level_required' => 0],
            ['slug' => 'flag-za', 'name' => 'Zuid-Afrika', 'description' => 'De Zuid-Afrikaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇿🇦', 'level_required' => 0],
            ['slug' => 'flag-ng', 'name' => 'Nigeria', 'description' => 'De Nigeriaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇳🇬', 'level_required' => 0],
            ['slug' => 'flag-ma', 'name' => 'Marokko', 'description' => 'De Marokkaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇲🇦', 'level_required' => 0],
            ['slug' => 'flag-sa', 'name' => 'Saoedi-Arabië', 'description' => 'De Saoedische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇦', 'level_required' => 0],
            ['slug' => 'flag-ae', 'name' => 'Ver. Arabische Emiraten', 'description' => 'De vlag van de VAE.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇪', 'level_required' => 0],
            ['slug' => 'flag-il', 'name' => 'Israël', 'description' => 'De Israëlische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇱', 'level_required' => 0],
            ['slug' => 'flag-th', 'name' => 'Thailand', 'description' => 'De Thaise vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇹🇭', 'level_required' => 0],
            ['slug' => 'flag-vn', 'name' => 'Vietnam', 'description' => 'De Vietnamese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇻🇳', 'level_required' => 0],
            ['slug' => 'flag-id', 'name' => 'Indonesië', 'description' => 'De Indonesische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇩', 'level_required' => 0],
            ['slug' => 'flag-ph', 'name' => 'Filipijnen', 'description' => 'De Filipijnse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇭', 'level_required' => 0],
            ['slug' => 'flag-my', 'name' => 'Maleisië', 'description' => 'De Maleisische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇲🇾', 'level_required' => 0],
            ['slug' => 'flag-sg', 'name' => 'Singapore', 'description' => 'De Singaporese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇬', 'level_required' => 0],
            ['slug' => 'flag-nz', 'name' => 'Nieuw-Zeeland', 'description' => 'De Nieuw-Zeelandse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇳🇿', 'level_required' => 0],
            ['slug' => 'flag-co', 'name' => 'Colombia', 'description' => 'De Colombiaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇴', 'level_required' => 0],
            ['slug' => 'flag-cl', 'name' => 'Chili', 'description' => 'De Chileense vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇱', 'level_required' => 0],
            ['slug' => 'flag-pe', 'name' => 'Peru', 'description' => 'De Peruaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇪', 'level_required' => 0],
            ['slug' => 'flag-ve', 'name' => 'Venezuela', 'description' => 'De Venezolaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇻🇪', 'level_required' => 0],
            ['slug' => 'flag-ec', 'name' => 'Ecuador', 'description' => 'De Ecuadoraanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇪🇨', 'level_required' => 0],
            ['slug' => 'flag-cu', 'name' => 'Cuba', 'description' => 'De Cubaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇺', 'level_required' => 0],
            ['slug' => 'flag-jm', 'name' => 'Jamaica', 'description' => 'De Jamaicaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇯🇲', 'level_required' => 0],
            ['slug' => 'flag-is', 'name' => 'IJsland', 'description' => 'De IJslandse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇸', 'level_required' => 0],
            ['slug' => 'flag-lu', 'name' => 'Luxemburg', 'description' => 'De Luxemburgse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇱🇺', 'level_required' => 0],
            ['slug' => 'flag-sr', 'name' => 'Suriname', 'description' => 'De Surinaamse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇷', 'level_required' => 0],
            ['slug' => 'flag-aw', 'name' => 'Aruba', 'description' => 'De Arubaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇼', 'level_required' => 0],
            ['slug' => 'flag-cw', 'name' => 'Curaçao', 'description' => 'De Curaçaose vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇨🇼', 'level_required' => 0],
            ['slug' => 'flag-pk', 'name' => 'Pakistan', 'description' => 'De Pakistaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇰', 'level_required' => 0],
            ['slug' => 'flag-bd', 'name' => 'Bangladesh', 'description' => 'De Bengalese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇧🇩', 'level_required' => 0],
            ['slug' => 'flag-ke', 'name' => 'Kenia', 'description' => 'De Keniaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇰🇪', 'level_required' => 0],
            ['slug' => 'flag-gh', 'name' => 'Ghana', 'description' => 'De Ghanese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇬🇭', 'level_required' => 0],
            ['slug' => 'flag-et', 'name' => 'Ethiopië', 'description' => 'De Ethiopische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇪🇹', 'level_required' => 0],
            ['slug' => 'flag-iq', 'name' => 'Irak', 'description' => 'De Iraakse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇶', 'level_required' => 0],
            ['slug' => 'flag-ir', 'name' => 'Iran', 'description' => 'De Iraanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇮🇷', 'level_required' => 0],
            ['slug' => 'flag-af', 'name' => 'Afghanistan', 'description' => 'De Afghaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇫', 'level_required' => 0],
            ['slug' => 'flag-sy', 'name' => 'Syrië', 'description' => 'De Syrische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇸🇾', 'level_required' => 0],
            ['slug' => 'flag-lb', 'name' => 'Libanon', 'description' => 'De Libanese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇱🇧', 'level_required' => 0],
            ['slug' => 'flag-jo', 'name' => 'Jordanië', 'description' => 'De Jordaanse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇯🇴', 'level_required' => 0],
            ['slug' => 'flag-ps', 'name' => 'Palestina', 'description' => 'De Palestijnse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇵🇸', 'level_required' => 0],
            ['slug' => 'flag-dz', 'name' => 'Algerije', 'description' => 'De Algerijnse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇩🇿', 'level_required' => 0],
            ['slug' => 'flag-tn', 'name' => 'Tunesië', 'description' => 'De Tunesische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇹🇳', 'level_required' => 0],
            ['slug' => 'flag-ly', 'name' => 'Libië', 'description' => 'De Libische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇱🇾', 'level_required' => 0],
            ['slug' => 'flag-al', 'name' => 'Albanië', 'description' => 'De Albanese vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇦🇱', 'level_required' => 0],
            ['slug' => 'flag-ba', 'name' => 'Bosnië-Herzegovina', 'description' => 'De Bosnische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇧🇦', 'level_required' => 0],
            ['slug' => 'flag-mk', 'name' => 'Noord-Macedonië', 'description' => 'De Macedonische vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇲🇰', 'level_required' => 0],
            ['slug' => 'flag-me', 'name' => 'Montenegro', 'description' => 'De Montenegrijnse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇲🇪', 'level_required' => 0],
            ['slug' => 'flag-xk', 'name' => 'Kosovo', 'description' => 'De Kosovaarse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇽🇰', 'level_required' => 0],
            ['slug' => 'flag-lt', 'name' => 'Litouwen', 'description' => 'De Litouwse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇱🇹', 'level_required' => 0],
            ['slug' => 'flag-lv', 'name' => 'Letland', 'description' => 'De Letse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇱🇻', 'level_required' => 0],
            ['slug' => 'flag-ee', 'name' => 'Estland', 'description' => 'De Estse vlag.', 'type' => 'flag', 'rarity' => 'common', 'price' => 40, 'css_class' => '🇪🇪', 'level_required' => 0],
        ];

        foreach ($items as $item) {
            ShopItem::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
